### ISSUE TITLE
Q&A: Operationalization Guidance

### ISSUE THREAD

**Issue by wdonno** [dmis-lab/self-biorag#1]
Hi, This looks like a brilliant implementation! If there is a better forum (Discord?) to ask these, please advise.  Also, if I am not the target audience, I understand:  I have a basic understanding of the technology but little programming skill or experience.
1. For ongoing use, is the intent that you feed tokenized result of a specific pubMed search to the model?  Are there examples of how to do this?  (Even schematic workflow to follow).  Sorry, It is not clear to me in the repo what information is related to training the model vs using the system.
2.  More complete working example script showing more detail of interface with vLLM (eg either all local or with dockerization of vLLM). For me, my GPU is too small so will likely use a cloud system like https://brev.dev/

Guidance on getting started for people in my demographic would be very much appreciated!

**Comment by minstar** [comment]
Hi @wdonno 
You could freely ask here: https://discord.gg/JxhHpTaH

1. The specific result of the PubMed document will be fed into the model as a tokenization result. The main point is that our generator model (selfbiorag-7b) identifies when to retrieve documents. If you just want to try our model, then you could use in an inference process.
2. Using only an inference process, you could easily load and use our model in 24GB size. If you still need a cloud system then I will take some time to find out how to use our process and make a guideline of it.

**Comment by wdonno** [comment]
Thanks! I will take a closer look and ask further questions at the discord.  Very much appreciate your response.
